.TH WAZZUF-EXTERNAL-TOOLS-INSTALL 1 "September 16, 2012"
.SH NAME
wazzuf-external-tools-install \- Download/install non-packaged tools to ease Wazzuf Ripper treatment.
.SH DESCRIPTION
\fBwazzuf-external-tools-install\fP is a shell script (bash) to
.B ease
.BR wazzuf-ripper (1)
treatment.
.PP
It can download/install some non-packaged tools to ~/wazzuf-ripper/external-tools as:
.TP
.B imdb-cli
retrieve IMdb informations (https://github.com/bgr/imdb-cli).
.TP
.B ccextractor
extract TS subtitles (CC) (http://ccextractor.sourceforge.net/).
.TP
.B tsMuxer
extract/demux BD subtitle (PGS) (http://www.videohelp.com/tools/tsMuxeR).
.PP
.SH SEE ALSO
.BR wazzuf-ripper (1)
,
.BR wazzuf-pre-ripper (1)
,
.BR wazzuf-ripper.conf (4)
.
.SH AUTHOR
wazzuf-ripper was written by Nicolas Perrin <booloki@lokizone.net>.
.PP
This manual page was written by Nicolas Perrin <booloki@lokizone.net>,
for the Debian project (and may be used by others).
