.TH WAZZUF-PRE-RIPPER 1 "September 15, 2012"
.SH NAME
wazzuf-pre-ripper \- DVD/BD Analyser for wazzuf-ripper.
.SH DESCRIPTION
\fBwazzuf-pre-ripper\fP is a shell script (bash) to
.B  analyse
DVD/BD, helping providing
.B wazzuf-ripper.conf (4)
for
.B wazzuf-ripper (1)
.
.PP
It can search for IMdb ID and download poster image.
.PP
It can also copy physical DVD to ISO file in order to ease ripping.
.PP
.SH SEE ALSO
.BR wazzuf-ripper (1),
.BR wazzuf-external-tools-install (1),
.BR wazzuf-ripper.conf (4).
.SH AUTHOR
wazzuf-pre-ripper was written by Nicolas Perrin <booloki@lokizone.net>.
.PP
This manual page was written by Nicolas Perrin <booloki@lokizone.net>,
for the Debian project (and may be used by others).
