#!/bin/bash
## nfo file function

# generate .nfo file
# need MERGE_OUTPUT
#      SIG_FILE_PATH
#      VIDEO_TYPE
#      TITLE_NAME
#      DATE
#      IMDB_ID
# return AUDIO_FILE
generate_nfo () {
  # Replace output file if exists
  echo "${MERGE_OUTPUT}" > "${MERGE_OUTPUT}.nfo"
  echo "" >> "${MERGE_OUTPUT}.nfo"

  # md5sum
  check_md5sum
  MD5=$(md5sum "${MERGE_OUTPUT}" | awk '{print($1);}')
  echo "md5: ${MD5}" >> "${MERGE_OUTPUT}.nfo"

  # Signature, if exists
  if [ -f "${SIG_FILE_PATH}" ]; then
    cat "${SIG_FILE_PATH}" >> "${MERGE_OUTPUT}.nfo"
  fi

  { echo ""
    echo "###################  IMdb Info  ###################"
    echo ""
  } >> "${MERGE_OUTPUT}.nfo"

  # Provided informations (from IMdb or not)
  case "${VIDEO_TYPE}" in
  MOVIE )
    echo "Title          : ${TITLE_NAME}" >> "${MERGE_OUTPUT}.nfo"
    if  [[ "${IMDB_DIRECTOR}" == "" || "${IMDB_DIRECTOR}" == "N/A" ]]; then
      echo "Director       : ${DIRECTOR_NAME}" >> "${MERGE_OUTPUT}.nfo"
    else
      echo "Director       : ${IMDB_DIRECTOR}" >> "${MERGE_OUTPUT}.nfo"
    fi
    echo "Release Date   : ${DATE}"  >> "${MERGE_OUTPUT}.nfo"
          ;;
  SHOW )
    echo "Show           : ${TITLE_NAME}" >> "${MERGE_OUTPUT}.nfo"
    echo "Season         : ${SEASON_NUMBER}" >> "${MERGE_OUTPUT}.nfo"
    if [[ "${MERGE_OUTPUT}" == *BONUS* || "${EPISODES_TOTAL_NUMBER}" == "" ]]; then
      echo "Episode Number : ${EPISODE_NUMBER}" >> "${MERGE_OUTPUT}.nfo"
    else
      echo "Episode Number : ${EPISODE_NUMBER}/${EPISODES_TOTAL_NUMBER}" >> "${MERGE_OUTPUT}.nfo"
    fi
    echo "Episode Title  : ${EPISODE_NAME}" >> "${MERGE_OUTPUT}.nfo"
    echo "Release Date   : ${DATE}" >> "${MERGE_OUTPUT}.nfo"
          ;;
  MUSIC )
    { echo "Title        : ${TITLE_NAME}"
      echo "Artist       : $ARTIST_NAME"
      echo "Release Date : ${DATE}"
    } >> "${MERGE_OUTPUT}.nfo"
          ;;
  esac

  # IMdb informations
  if [[ ! "${IMDB_ID}" == "" ]]; then
    { echo "Writer(s)      : ${IMDB_WRITER}"
      echo "Actors(s)      : ${IMDB_ACTORS}"
      echo "Genre(s)       : ${IMDB_GENRE}"
      echo "Plot           : ${IMDB_PLOT}"
      echo "Rated          : ${IMDB_RATED}"
      echo "IMdb Rating    : ${IMDB_RATING}"
      echo "IMdb Votes     : ${IMDB_VOTES}"
      echo "Runtime        : ${IMDB_RUNTIME}"
    } >> "${MERGE_OUTPUT}.nfo"
  fi

  { echo ""
    echo "###################  Media Info  ###################"
    echo ""
    mediainfo "${MERGE_OUTPUT}"
  } >> "${MERGE_OUTPUT}.nfo"

}
