#! /bin/bash
# Wazzuf Ripper
# DVD/BD rip external tools download/install
# booloki@lokizone.net

PATH_FILE="/etc/wazzuf-ripper/wazzuf-path.conf"
source $PATH_FILE

source $FUNCTIONS_CHECK
mkdir -p $EXTERNAL_TOOLS_PATH
cd $EXTERNAL_TOOLS_PATH

# imdb-cli - no licence provided, but github so should be Open Source.
# https://github.com/bgr/imdb-cli
# + API http://www.imdbapi.com/
IMDBCLI_GIT="git://github.com/bgr/imdb-cli"
IMDBCLI_DIRECTORY="imdb-cli"
IMDBCLI_TOOL="../$EXTERNAL_TOOLS_PATH/$IMDBCLI_DIRECTORY/imdbtool.py"
echo -ne "\n*************************************\n"
echo -ne " imdb-cli can retrieve IMdb informations.\n"
echo -ne " Do you want to download/install imdb-cli ? (N/y)\n"
read answer
case $answer in
y* | Y* )
	# Check git
	if [ ! -x "/usr/bin/git" ]; then
		echo -ne "\n *************************************\n"
		echo -ne " Please install git !\n"
		echo -ne " Or manually download imdb-cli at https://github.com/bgr/imdb-cli/downloads\n"
		echo -ne " and extract archive to $EXTERNAL_TOOLS_PATH/$IMDBCLI_DIRECTORY/\n"
		echo -ne " Skip imdb-cli download/install.\n"
		echo -ne " *************************************\n" && sleep 1
	else
		git clone $IMDBCLI_GIT
	fi
	;;
* )
	echo -ne " Skip imdb-cli download/install.\n"
	;;
esac

# ccextractor - GPL 2.0
# http://ccextractor.sourceforge.net
CCEXTRACTOR_URL="http://sourceforge.net/projects/ccextractor/files/latest/download?source=files"
CCEXTRACTOR_FILE="download?source=files"
CCEXTRACTOR_DIRECTORY="ccextractor.0.63/linux"
CCEXTRACTOR_TOOL="../$EXTERNAL_TOOLS_PATH/$CCEXTRACTOR_DIRECTORY/ccextractor"
echo -ne "\n*************************************\n"
echo -ne " ccextractor can extract TS subtitles (CC): .srt files.\n"
echo -ne " Do you want to download/build ccextractor ? (N/y)\n"
read answer
case $answer in
y* | Y* )
	wget -nc $CCEXTRACTOR_URL
	check_7z
	7z x $CCEXTRACTOR_FILE
	# Check g++
	if [ ! -x "/usr/bin/g++" ]; then
		echo -ne "\n *************************************\n"
		echo -ne " Please install g++ !\n"
		echo -ne " Skip ccextractor build.\n"
		echo -ne " *************************************\n" && sleep 1
	else
		cd $CCEXTRACTOR_DIRECTORY
		./build
		cd ../../
	fi
	;;
* )
	echo -ne " Skip ccextractor download/build.\n"
	;;
esac

# tsMuxer (Freeware No longer developed)
# http://www.videohelp.com/tools/tsMuxeR
TSMUXER_URL_BASE="http://www.videohelp.com/download"
TSMUXER_FILENAME_BASE="tsMuxeR_1.10.6.tar.gz"
TSMUXER_URL="$TSMUXER_URL_BASE/$TSMUXER_FILENAME_BASE"
TSMUXER_DIRECTORY="tsmuxer"
TSMUXER_TOOL="../$EXTERNAL_TOOLS_PATH/$TSMUXER_DIRECTORY/tsMuxeR"
echo -ne "\n*************************************\n"
echo -ne " tsMuxer can extract/demux BD subtitle (PGS): .sup files.\n"
echo -ne " Do you want to download/install tsMuxer ? (N/y)\n"
read answer
case $answer in
y* | Y* )
	wget $TSMUXER_URL -O tsmuxer.html
	TSMUXER_URL_FILE=`grep "click here" tsmuxer.html | cut -d '"' -f4`
	rm tsmuxer.html
	wget -nc $TSMUXER_URL_FILE
	TSMUXER_FILE=`echo $TSMUXER_URL_FILE | cut -d '/' -f 5`
	mkdir -p $TSMUXER_DIRECTORY
	mv $TSMUXER_FILE $TSMUXER_FILENAME_BASE
	tar xvzf $TSMUXER_FILENAME_BASE -C $TSMUXER_DIRECTORY
	;;
* )
	echo -ne " Skip tsMuxer download/install.\n"
	;;
esac

exit 0
