.TH WAZZUF-RIPPER.CONF 4 "September 15, 2012"
.SH NAME
wazzuf-ripper.conf \- Wazzuf Ripper configuration file
.SH DESCRIPTION
TODO
.PP
.SH SEE ALSO
.BR wazzuf-ripper (1),
.BR wazzuf-external-tools-install (1),
.BR wazzuf-pre-ripper (1).
.SH AUTHOR
wazzuf-ripper was written by Nicolas Perrin <booloki@lokizone.net>.
.PP
This manual page was written by Nicolas Perrin <booloki@lokizone.net>,
for the Debian project (and may be used by others).
